### PR TITLE
Updates for newest Adminer versions

### PR DESCRIPTION
**Pull request by HorlogeSkynet**
Hey there !

For some weeks now, the select lang has been misplaced (I think it was due to the v4.6.0 but I'm really not sure).
There are some changes (fully subjective) to re-center it a bit, feel free to edit this PR your way.

Bye :wave:

PS : I still hope you will consider drafting releases for this awesome styles-sheet (https://github.com/pepa-linha/Adminer-Design-Dark/pull/1#issuecomment-402028257).

### CODE REVIEW

**Comment by pepa-linha** [comment]
Hello,

Thanks for your PR, I will check it after test new Adminer version.

For the comment you mentioned,  could you give me some tips how to do that? I am not sure I understand. Did you mean relationship between this repository and Adminer repository? Maybe, insert Git tags for commits? Thank you.

**Comment by HorlogeSkynet** [comment]
Hello Pepa,

Awesome, keep me posted about this !

---

Yes of course, GitHub has pretty well-made guides to achieve this (see links below).
The idea is basically to create Git tags, and then [releases on GitHub](https://github.com/pepa-linha/Adminer-Design-Dark/releases) (optional step).
For the versioning (`vX.Y.Z`), maybe you could follow the Adminer's one (i.e. a Git tag created once this PR is merged could be `v4.7.0`) ; It would help administrators choosing a version of your styles-sheet in function of the Adminer version they use.
And finally, and this was the goal of (https://github.com/pepa-linha/Adminer-Design-Dark/pull/1#issuecomment-402028257), it would be very cool if you could sign these tags with a key that you keep private on your own.

Bye :wave:

## Refs

* [Git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging)
* [Versioning](https://semver.org/)
* [Signing Git tags](https://help.github.com/articles/signing-tags/) (follow the "Further Reading" at the bottom to generate and add your GPG key to GitHub :wink:)
* [Git and GPG Key](https://help.github.com/articles/telling-git-about-your-signing-key/#telling-git-about-your-gpg-key)

**Comment by pepa-linha** [comment]
I am sorry, I do not think so that Git tags are good idea because then I should check every time new Adminer versions and change tags in this repository. I want avoid this.

Thanks for your comments to lang `<select>`, it has bad styles now. I will fix it.

**Comment by HorlogeSkynet** [comment]
I understand what you mean, it was just an idea though.

For the "users", versioning is always a good idea, if only for the purpose of allowing us to follow with ease.
You can opt for your own semantic over here, and it could start as `v1.0.0` now for example.

But anyway, it's up to you !
@+ :wave:

**Comment by pepa-linha** [comment]
Yep, I know semantic versioning. I will think about it :-) Thank you for your info. 👍

**Comment by HorlogeSkynet** [comment]
Hey @pepa-linha !
Any news on this ? Thanks bye :wave:

**Comment by HorlogeSkynet** [comment]
Up 👍

**Review by 06Games — APPROVED** [review]

**Comment by pepa-linha** [comment]
Hi, I'm sorry for not responding. I'm going to update and thanks for your changes.

I've been thinking about semantic versioning, but I don't really like either version. Versioning the same as Adminer is not a good idea for me. I'd rather start the standard version from 1.0.0 and after some changes I change the version to 1.0.1 (example, and a compatible version of Adminer will be published in the readme).

I will check it now.

(I did theme only for my use and I don't use Windows and any browser other than Chrome. I know this theme is not perfect at all :-))

**Pull request closed without merging**
