### PR TITLE
Fix footer style

### PR DESCRIPTION
**Pull request by osk2**
The style seems outdated, footer is broken

screen shot 2018-06-13 at 10 11 13 am

I add some style to fix footer :)

### CODE REVIEW

**Comment by HorlogeSkynet** [comment]
Hi @pepa-linha @osk2, I've just tried it and it effectively fixes this glitch introduced by a previous version of Adminer during last winter.
This should be merged :+1:

Bye :wave:

**Comment by pepa-linha** [comment]
@osk2 Thank you for that. I hope I will check this PR very soon.
@HorlogeSkynet Thank you for trying.

👍

**Comment by pepa-linha** [comment]
I made some changes on the footer. I really don't like generated HTML by Adminer. 😈

@osk2 I can't used your code because I saw some artefacts. Probably thanks to bad colors :-)

**Comment by osk2** [comment]
I tried your fix, it works perfectly 👍 

I'm closing this PR.

**Comment by HorlogeSkynet** [comment]
Thanks for this, @pepa-linha could you consider creating releases for this "project" ?
If so, maybe it would be good to follow the Adminer versioning history to _match_ a working version of the styles-sheet with an explicit designated Adminer version.
And if so (again), maybe you could [add a GPG key](https://help.github.com/articles/adding-a-new-gpg-key-to-your-github-account/) to sign your work (as [CSS "attacks" are possible](https://github.com/jbtronics/CrookedStyleSheets)...).

Thanks for hearing me out, bye :wave:

**Pull request closed without merging**
